### ISSUE TITLE
This is a new repo?

### ISSUE THREAD

**Issue by webcoderkz** [dazuaz/responsive-images-loader#2]
Is this the main repo for improved responsive-loader for now? Or it would be renamed?

**Comment by dazuaz** [comment]
@webcoderkz: this was a temporary repo, the original maintainer transferred the main repo to me recently, you can find the latest release of responsive loader here https://github.com/dazuaz/responsive-loader

you can `npm install responsive-loader` to upgrade to version 2.0.0 which contains all new changes.
